// /// Flutter icons MyFlutterApp
// /// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
// /// This font was generated by FlutterIcon.com, which is derived from Fontello.
// ///
// /// To use this font, place it in your fonts/ directory and include the
// /// following in your pubspec.yaml
// ///
// /// flutter:
// ///   fonts:
// ///    - family:  MyFlutterApp
// ///      fonts:
// ///       - asset: fonts/MyFlutterApp.ttf
// ///
// /// 
// /// * Material Design Icons, Copyright (C) Google, Inc
// ///         Author:    Google
// ///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
// ///         Homepage:  https://design.google.com/icons/
// /// * Typicons, (c) Stephen Hutchings 2012
// ///         Author:    Stephen Hutchings
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://typicons.com/
// /// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
// ///         Author:    John Caserta
// ///         License:   SIL (http://scripts.sil.org/OFL)
// ///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
// /// * Linearicons Free, Copyright (C) Linearicons.com
// ///         Author:    Perxis
// ///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
// ///         Homepage:  https://linearicons.com
// ///
// import 'package:flutter/widgets.dart';

// class MyFlutterApp {
//   MyFlutterApp._();

//   static const _kFontFam = 'MyFlutterApp';
//   static const String? _kFontPkg = null;

  
//   static const IconData doc_text = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData exit_up = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }
